### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by Brendan-McWalters** [deontologician/netezza_sqlalchemy#1]
I'm not quite sure how to use this dialect. Is it a wrapper or do I have to put it in the sqlalchemy hierarchy?

**Comment by deontologician** [comment]
You just need to copy the `netezza_dialect.py` somewhere that python can find it, so when you do `import netezza_dialect` it imports successfully (this could be just pasting it in your root or whatever).

It takes care of registering the `netezza://` prefix with sqlalchemy, so you don't need to do anything special there, and the script in the README should work for you. Let me know if you have any more questions. I never took the time to package it properly, and as I don't have access to a Netezza machine any more, it's unlikely I'll be able to make further improvements. Pull requests welcome!

**Comment by Brendan-McWalters** [comment]
So when I do that, it coughs 

```
$ python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> import netezza_dialect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netezza_dialect.py", line 27, in <module>
    class NVARCHAR(sqltypes.NVARCHAR):
  File "netezza_dialect.py", line 31, in NVARCHAR
    unicode_error=coerce_nvarchar):
NameError: name 'coerce_nvarchar' is not defined
```

What version of sqlalchemy did you develop this with? There were some notes in the SQL Alchemy documentation (http://docs.sqlalchemy.org/en/rel_1_0/dialects/index.html) which say that post version 0.8 the some of the built in dialects were changed. Pull request may be following.

**Comment by deontologician** [comment]
I believe 0.8 or 0.9, 1.0 hadn't come out back then

**Comment by deontologician** [comment]
I think the coerce_nvarchar function was defined in our internal code. This was cleaned up from another file that was much messier, and it's likely I just forgot to copy it over. If I recall correctly, it was just a conversion function that handled encoding errors. You can probably just mock it out and see if it receives anything when you run it

**Comment by Brendan-McWalters** [comment]
Awesome, Thanks for the help.
