### ISSUE TITLE
'NVARCHAR' not defined

### ISSUE THREAD

**Issue by gtnbz2nyte** [deontologician/netezza_sqlalchemy#2]
Following your advice on the issue prior to this post, I pasted netezza_dialect.py on my root Python folder and attempted to import it, but then I received this error:

```
In[73]: import netezza_dialect

Traceback (most recent call last):
  File "C:\Anaconda3\envs\python_2_7_Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-72-9cf57defda0d>", line 1, in <module>
    import netezza_dialect
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\python_2_7_Anaconda\netezza_dialect.py", line 32, in <module>
    class NAME(NVARCHAR):
NameError: name 'NVARCHAR' is not defined
```

**Comment by deontologician** [comment]
Hi @gtnbz2nite I don't have the ability to support this module at the moment (I lack time and access to a Netezza server). I hope you'll be able to get some use from it, but you'll likely need to debug it yourself.

That being said, I am guessing this is related to your sqlalchemy version. I think I wrote this back in the pre-1.0 sqlalchemy days. Here the NVARCHAR variable is coming from sqlalchemy.sqltypes, which may not exist any more
